// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package models

import (
	"database/sql"
)

type Transaction struct {
	ID          int64
	Date        string
	Code        sql.NullString
	Description string
	Amount      int64
}
