// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: query.sql

package models

import (
	"context"
	"database/sql"

	types "finance/internal/types"
)

const addLabelToTransaction = `-- name: AddLabelToTransaction :exec
UPDATE transactions SET label_id = ? WHERE id = ?
`

type AddLabelToTransactionParams struct {
	LabelID sql.NullInt64
	ID      int64
}

func (q *Queries) AddLabelToTransaction(ctx context.Context, arg AddLabelToTransactionParams) error {
	_, err := q.db.ExecContext(ctx, addLabelToTransaction, arg.LabelID, arg.ID)
	return err
}

const createTransaction = `-- name: CreateTransaction :exec
INSERT INTO transactions (
  date, code, description, amount, balance
) VALUES (
  ?, ?, ?, ?, ?
)
`

type CreateTransactionParams struct {
	Date        types.Date
	Code        sql.NullString
	Description string
	Amount      int64
	Balance     int64
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) error {
	_, err := q.db.ExecContext(ctx, createTransaction,
		arg.Date,
		arg.Code,
		arg.Description,
		arg.Amount,
		arg.Balance,
	)
	return err
}

const deleteTransaction = `-- name: DeleteTransaction :exec
DELETE FROM transactions
WHERE id = ?
`

func (q *Queries) DeleteTransaction(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTransaction, id)
	return err
}

const findLabel = `-- name: FindLabel :one
SELECT id, name FROM label WHERE id = ?
`

func (q *Queries) FindLabel(ctx context.Context, id int64) (Label, error) {
	row := q.db.QueryRowContext(ctx, findLabel, id)
	var i Label
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, date, code, description, amount, balance, label_id FROM transactions
WHERE id = ? LIMIT 1
`

func (q *Queries) GetTransaction(ctx context.Context, id int64) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, getTransaction, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.Code,
		&i.Description,
		&i.Amount,
		&i.Balance,
		&i.LabelID,
	)
	return i, err
}

const getTransaction2 = `-- name: GetTransaction2 :one
SELECT t.id, t.date, t.code, t.description, t.amount, t.balance, t.label_id, l.name as label from transactions t LEFT JOIN label l on l.id = t.label_id where t.id = ?
`

type GetTransaction2Row struct {
	ID          int64
	Date        types.Date
	Code        sql.NullString
	Description string
	Amount      int64
	Balance     int64
	LabelID     sql.NullInt64
	Label       string
}

func (q *Queries) GetTransaction2(ctx context.Context, id int64) (GetTransaction2Row, error) {
	row := q.db.QueryRowContext(ctx, getTransaction2, id)
	var i GetTransaction2Row
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.Code,
		&i.Description,
		&i.Amount,
		&i.Balance,
		&i.LabelID,
		&i.Label,
	)
	return i, err
}

const lastMonthTransactions = `-- name: LastMonthTransactions :many
SELECT id, date, code, description, amount, balance, label_id FROM transactions WHERE strftime('%Y-%m', date) = (SELECT strftime('%Y-%m', date) FROM transactions order by date desc limit 1) ORDER BY id
`

func (q *Queries) LastMonthTransactions(ctx context.Context) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, lastMonthTransactions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.Code,
			&i.Description,
			&i.Amount,
			&i.Balance,
			&i.LabelID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLabels = `-- name: ListLabels :many
SELECT id, name FROM label
`

func (q *Queries) ListLabels(ctx context.Context) ([]Label, error) {
	rows, err := q.db.QueryContext(ctx, listLabels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Label
	for rows.Next() {
		var i Label
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactions = `-- name: ListTransactions :many
SELECT id, date, code, description, amount, balance, label_id FROM transactions
ORDER BY date
`

func (q *Queries) ListTransactions(ctx context.Context) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, listTransactions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.Code,
			&i.Description,
			&i.Amount,
			&i.Balance,
			&i.LabelID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
